---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xuni.
--- DateTime: 2022/7/14 16:06
---
local voucherId = ARGV[1]

local userId = ARGV[2]

local orderId = ARGV[3]

local stockKey = 'seckill:stock:' .. voucherId

local orderKey = 'seckill:order:' .. voucherId

-- 脚本业务
-- 判断库存是否充足
if tonumber(redis.call('get', stockKey)) <= 0 then
    return 1
end
-- 判断用户是否下过单了
if redis.call('sismember', orderKey, userId) == 1 then
    return 2
end

-- 扣库存
redis.call('incrby', stockKey, -1)
-- 添加用户
redis.call('sadd', orderKey, userId)
-- 发送消息到消息队列中   XADD streams.orders * k1 v1 k2 v2
redis.call('xadd', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)
return 0
